"""
10_validate_and_run.py - Master runner: executes all scripts in order, validates data, reports.

This is the single entry point for the entire data generation pipeline.
It does three things:
  1. Runs scripts 01–09 sequentially, passing a shared DataStore between them
     so that each script can reference IDs generated by earlier scripts.
  2. After all data is inserted, runs a comprehensive validation suite that
     checks FK integrity, date constraints, uniqueness, and invoice math.
  3. Reports row counts, timing, and any validation failures.

Design decisions:
  - Sequential execution (not parallel) because each script depends on IDs
    from earlier scripts.  The FK dependency chain is:
      01_lookups → 02_core_entities → 03_accounts_sims → 04_subscriptions
      → 05_network → 06_network_events → 07_usage_cdrs → 08_billing → 09_crm
  - importlib.util.spec_from_file_location is used instead of importlib.import_module
    because Python can’t import modules whose names start with a digit (01_, 02_, etc.).
  - All inserts share one DB connection, so on failure we rollback everything
    (all-or-nothing) rather than leaving the database in a half-populated state.
  - --scale multiplies all row counts linearly: 0.5x for quick testing,
    5.0x for load testing.  Clamped to [0.1, 10.0] to prevent accidents.
  - --seed resets both Faker and random so the full dataset is reproducible.
  - Validation queries use NOT EXISTS subqueries (not JOINs) to efficiently
    detect orphaned FK references even on large tables.

Usage:
    python 10_validate_and_run.py [--scale 1.0] [--seed 42]
"""

import sys, os, time, argparse, importlib.util

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, BASE_DIR)

from setup import get_connection, set_seed, DataStore, print_table_count


def _load_module(filename):
    """Load a Python module from a file path (works even if name starts with a digit)."""
    filepath = os.path.join(BASE_DIR, filename)
    spec = importlib.util.spec_from_file_location(filename.replace(".py", ""), filepath)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


# ---------------------------------------------------------------------------
# Script list — executed in this exact order.
# The order follows the FK dependency graph: each script only references
# tables that were populated by earlier scripts.
# ---------------------------------------------------------------------------
SCRIPTS = [
    "01_lookups.py",
    "02_core_entities.py",
    "03_accounts_sims.py",
    "04_subscriptions.py",
    "05_network.py",
    "06_network_events.py",
    "07_usage_cdrs.py",
    "08_billing.py",
    "09_crm.py",
]

# ---------------------------------------------------------------------------
# All tables in the schema, ordered by domain.
# Used for row-count reporting after generation completes.
# ---------------------------------------------------------------------------
ALL_TABLES = [
    "billing_cycles", "departments", "employee_roles", "services",
    "overage_policies", "network_technologies", "payment_methods",
    "addons", "discounts_promotions",
    "customers", "customer_addresses", "employees", "products", "plans",
    "accounts", "contracts", "sim_cards", "devices",
    "subscriptions", "subscription_addons", "subscription_status_history",
    "device_assignments", "sim_card_subscription_history",
    "network_sites", "cell_towers", "tower_sectors", "coverage_zones",
    "roaming_partners",
    "network_alarms", "outages", "employee_assignments",
    "usage_cdr_calls", "usage_cdr_sms", "usage_cdr_data",
    "usage_aggregates_daily",
    "invoices", "invoice_items", "payments", "billing_runs",
    "crm_tickets", "crm_interactions", "ticket_status_history",
]

# ---------------------------------------------------------------------------
# Validation rules
# ---------------------------------------------------------------------------
# These mirror the constraints defined in the DDL (message.txt).  Running
# them after data generation catches bugs in the generator scripts that
# would otherwise only surface when the application queries the data.

# Foreign key relationships to validate: (child_table, child_col, parent_table, parent_col)
# Each entry checks that every non-NULL child_col value exists in parent_table.
FK_CHECKS = [
    ("customer_addresses", "customer_id", "customers", "customer_id"),
    ("accounts", "customer_id", "customers", "customer_id"),
    ("accounts", "billing_cycle_id", "billing_cycles", "billing_cycle_id"),
    ("contracts", "customer_id", "customers", "customer_id"),
    ("contracts", "account_id", "accounts", "account_id"),
    ("employees", "department_id", "departments", "department_id"),
    ("employees", "role_id", "employee_roles", "role_id"),
    ("products", "service_id", "services", "service_id"),
    ("plans", "product_id", "products", "product_id"),
    ("plans", "overage_policy_id", "overage_policies", "overage_policy_id"),
    ("subscriptions", "account_id", "accounts", "account_id"),
    ("subscriptions", "plan_id", "plans", "plan_id"),
    ("subscriptions", "sim_id", "sim_cards", "sim_id"),
    ("subscription_addons", "subscription_id", "subscriptions", "subscription_id"),
    ("subscription_addons", "addon_id", "addons", "addon_id"),
    ("subscription_status_history", "subscription_id", "subscriptions", "subscription_id"),
    ("device_assignments", "device_id", "devices", "device_id"),
    ("device_assignments", "subscription_id", "subscriptions", "subscription_id"),
    ("cell_towers", "site_id", "network_sites", "site_id"),
    ("tower_sectors", "tower_id", "cell_towers", "tower_id"),
    ("tower_sectors", "technology_id", "network_technologies", "technology_id"),
    ("coverage_zones", "sector_id", "tower_sectors", "sector_id"),
    ("network_alarms", "tower_id", "cell_towers", "tower_id"),
    ("network_alarms", "sector_id", "tower_sectors", "sector_id"),
    ("outages", "site_id", "network_sites", "site_id"),
    ("usage_cdr_calls", "subscription_id", "subscriptions", "subscription_id"),
    ("usage_cdr_sms", "subscription_id", "subscriptions", "subscription_id"),
    ("usage_cdr_data", "subscription_id", "subscriptions", "subscription_id"),
    ("usage_aggregates_daily", "subscription_id", "subscriptions", "subscription_id"),
    ("invoices", "account_id", "accounts", "account_id"),
    ("invoice_items", "invoice_id", "invoices", "invoice_id"),
    ("payments", "account_id", "accounts", "account_id"),
    ("billing_runs", "billing_cycle_id", "billing_cycles", "billing_cycle_id"),
    ("crm_tickets", "customer_id", "customers", "customer_id"),
    ("crm_interactions", "ticket_id", "crm_tickets", "ticket_id"),
    ("ticket_status_history", "ticket_id", "crm_tickets", "ticket_id"),
    ("employee_assignments", "employee_id", "employees", "employee_id"),
]

# Date/time CHECK constraints to validate: (table, start_col, end_col)
# Ensures end >= start wherever the DDL has a CHECK like (end_date >= start_date).
DATE_CHECKS = [
    ("contracts", "start_date", "end_date"),
    ("subscriptions", "activation_date", "end_date"),
    ("subscription_addons", "activation_date", "deactivation_date"),
    ("device_assignments", "assigned_from", "assigned_to"),
    ("roaming_partners", "agreement_start", "agreement_end"),
    ("network_alarms", "raised_at", "cleared_at"),
    ("outages", "start_time", "end_time"),
    ("employee_assignments", "start_time", "end_time"),
    ("billing_runs", "period_start", "period_end"),
    ("billing_runs", "run_started_at", "run_finished_at"),
    ("invoices", "billing_period_start", "billing_period_end"),
    ("invoices", "issue_date", "due_date"),
    ("crm_tickets", "created_at", "closed_at"),
    ("sim_card_subscription_history", "start_date", "end_date"),
    ("usage_cdr_calls", "event_start_time", "event_end_time"),
    ("usage_cdr_data", "session_start", "session_end"),
]

# UNIQUE constraints to validate: (table, column)
# Checks that every column marked UNIQUE in the DDL has no duplicates.
UNIQUE_CHECKS = [
    ("customers", "email"),
    ("accounts", "account_number"),
    ("contracts", "contract_number"),
    ("sim_cards", "iccid"),
    ("sim_cards", "imsi"),
    ("sim_cards", "msisdn"),
    ("subscriptions", "subscription_number"),
    ("invoices", "invoice_number"),
    ("network_sites", "site_code"),
    ("cell_towers", "tower_code"),
    ("products", "product_code"),
    ("billing_cycles", "cycle_name"),
    ("departments", "department_name"),
    ("employee_roles", "role_name"),
    ("services", "service_name"),
    ("payment_methods", "method_name"),
    ("network_technologies", "technology_name"),
    ("overage_policies", "policy_name"),
    ("employees", "email"),
]


def validate(conn):
    """Run all validation checks against the populated database.

    Checks performed:
      1. Row counts:       prints how many rows each table has.
      2. FK integrity:     ensures no orphaned child rows.
      3. Date constraints: ensures end >= start for all temporal pairs.
      4. Uniqueness:       ensures no duplicate values in UNIQUE columns.
      5. Invoice math:     ensures invoice totals = sum of their line items.
    """
    cur = conn.cursor()
    print("\n" + "=" * 60)
    print("VALIDATION")
    print("=" * 60)

    # 1. Row counts
    print("\n--- Row Counts ---")
    total_rows = 0
    for table in ALL_TABLES:
        count = print_table_count(cur, table)
        total_rows += count
    print(f"\n  TOTAL: {total_rows} rows across {len(ALL_TABLES)} tables")

    # 2. FK checks — find child rows that reference non-existent parent rows.
    # Uses NOT EXISTS (correlated subquery) which is efficient on indexed PKs.
    print("\n--- Foreign Key Checks ---")
    fk_errors = 0
    for child_table, child_col, parent_table, parent_col in FK_CHECKS:
        cur.execute(f"""
            SELECT COUNT(*) FROM {child_table} c
            WHERE c.{child_col} IS NOT NULL
              AND NOT EXISTS (
                SELECT 1 FROM {parent_table} p WHERE p.{parent_col} = c.{child_col}
              )
        """)
        orphans = cur.fetchone()[0]
        if orphans > 0:
            print(f"  FAIL: {child_table}.{child_col} -> {parent_table}.{parent_col}: {orphans} orphaned rows")
            fk_errors += orphans
        else:
            print(f"  OK: {child_table}.{child_col} -> {parent_table}.{parent_col}")
    if fk_errors == 0:
        print(f"  All FK checks passed!")

    # 3. Date checks — verify that end >= start for all nullable end columns.
    # Only checks rows where the end column is NOT NULL (NULL means "ongoing").
    print("\n--- Date/Time Constraint Checks ---")
    date_errors = 0
    for table, start_col, end_col in DATE_CHECKS:
        cur.execute(f"""
            SELECT COUNT(*) FROM {table}
            WHERE {end_col} IS NOT NULL AND {end_col} < {start_col}
        """)
        violations = cur.fetchone()[0]
        if violations > 0:
            print(f"  FAIL: {table}.{end_col} < {table}.{start_col}: {violations} violations")
            date_errors += violations
        else:
            print(f"  OK: {table} ({start_col} <= {end_col})")
    if date_errors == 0:
        print(f"  All date checks passed!")

    # 4. Unique checks — detect duplicate values in columns with UNIQUE constraints.
    # GROUP BY + HAVING COUNT > 1 finds any duplicate values.
    print("\n--- Uniqueness Checks ---")
    unique_errors = 0
    for table, col in UNIQUE_CHECKS:
        cur.execute(f"""
            SELECT {col}, COUNT(*) FROM {table}
            WHERE {col} IS NOT NULL
            GROUP BY {col} HAVING COUNT(*) > 1
        """)
        dupes = cur.fetchall()
        if dupes:
            print(f"  FAIL: {table}.{col}: {len(dupes)} duplicate values")
            unique_errors += len(dupes)
        else:
            print(f"  OK: {table}.{col}")
    if unique_errors == 0:
        print(f"  All uniqueness checks passed!")

    # 5. Invoice total vs items — verify that invoice.total_amount equals
    # the sum of its invoice_items.line_amount (within ±0.02 for float rounding).
    print("\n--- Invoice Total vs Items Check ---")
    cur.execute("""
        SELECT i.invoice_id, i.total_amount,
               COALESCE(SUM(ii.line_amount), 0) AS items_total
        FROM invoices i
        LEFT JOIN invoice_items ii ON ii.invoice_id = i.invoice_id
        GROUP BY i.invoice_id, i.total_amount
        HAVING ABS(i.total_amount - COALESCE(SUM(ii.line_amount), 0)) > 0.02
    """)
    mismatches = cur.fetchall()
    if mismatches:
        print(f"  WARNING: {len(mismatches)} invoices have total != sum(items) (tolerance 0.02)")
    else:
        print(f"  OK: All invoice totals match their items")

    print("\n" + "=" * 60)
    total_errors = fk_errors + date_errors + unique_errors
    if total_errors == 0:
        print("ALL VALIDATION CHECKS PASSED!")
    else:
        print(f"TOTAL ERRORS: {total_errors}")
    print("=" * 60)


def main():
    parser = argparse.ArgumentParser(description="Generate synthetic telecom data")
    parser.add_argument("--scale", type=float, default=1.0, help="Scale factor for row counts (0.1 to 10.0)")
    parser.add_argument("--seed", type=int, default=42, help="Random seed for reproducibility")
    args = parser.parse_args()

    scale = max(0.1, min(10.0, args.scale))
    set_seed(args.seed)

    print(f"Scale: {scale}x | Seed: {args.seed}")
    print("=" * 60)

    start_time = time.time()
    conn = get_connection()
    store = DataStore()

    try:
        for script_file in SCRIPTS:
            step_start = time.time()
            label = script_file.replace(".py", "")
            print(f"\n--- Running {label} ---")
            mod = _load_module(script_file)
            mod.generate(conn, scale, store)
            step_elapsed = time.time() - step_start
            print(f"  ({step_elapsed:.1f}s)")

        validate(conn)
        conn.commit()

    except Exception as e:
        conn.rollback()
        print(f"\nERROR: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
    finally:
        conn.close()

    elapsed = time.time() - start_time
    print(f"\nTotal execution time: {elapsed:.1f}s")


if __name__ == "__main__":
    main()
